### ISSUE TITLE
MUMmer programs not found in path 

### ISSUE THREAD

**Issue by mthang** [sanger-pathogens/pymummer#21]
Hi , I have no clue why did the installation of pymummer failed even the following programs are in the right folder.  I typed "sudo pip3 install pymummer" and I keep getting this error message

nucmer -> /home/ec2-user/software/MUMmer3.23/nucmer
delta-filter -> /home/ec2-user/software/MUMmer3.23/delta-filter
show-coords -> /home/ec2-user/software/MUMmer3.23/show-coords
show-snps -> /home/ec2-user/software/MUMmer3.23/show-snps

Error message.
Complete output from command python setup.py egg_info:
    Checking MUMmer programs found in path:
       NOT FOUND        nucmer
       NOT FOUND        show-coords
       NOT FOUND        show-snps
       NOT FOUND        delta-filter
    Cannot install because some programs from the MUMer package not found.

**Comment by andrewjpage** [comment]
Are these programs available in your PATH? So if you type just 'nucmer' on
the command line, what happens?

**Comment by mthang** [comment]
Yes. They are in my PATH. When I typed "nucmer" or other commands, I can see this 
USAGE: nucmer  [options]  <Reference>  <Query>
USAGE: show-snps  [options]  <deltafile>
...

I just did a temporarily fix by doing the following.

required_progs = ['/usr/local/bin/nucmer', '/usr/local/bin/show-coords', '/usr/local/bin/show-snps', '/usr/local/bin/delta-filter']

Actually, it is very odd when I typed "python setup.py install" in the pymummer folder . The error message occurs like above. However, if I just copied the "setup.py" to other location and typed "python setup.py" . I will get the following message

Checking MUMmer programs found in path:
          OK    nucmer
          OK    show-coords
          OK    show-snps
          OK    delta-filter

**Comment by andrewjpage** [comment]
Just a note to say you need to be running python3, on many systems 'python' defaults to 2.7, which is incompatible.

**Comment by ftian9** [comment]
@mthang It is because when you use `sudo`, the $PATH will not include `/usr/local/bin`.
