### ISSUE TITLE
Python 3 pip installation failing

### ISSUE THREAD

**Issue by zmunro** [sanger-pathogens/pymummer#35]
I have tried running installation with python3.6, 3.7, and 3.8 and I get a similar error message with each:
```
$ python3.6 -m pip install pymummer
Collecting pymummer
  Cache entry deserialization failed, entry ignored
  Cache entry deserialization failed, entry ignored
  Downloading https://files.pythonhosted.org/packages/9f/a4/78890f48a84be3d4733262327da70220be8e11147c7d58b87ea979a0f866/pymummer-0.11.0.tar.gz
    Complete output from command python setup.py egg_info:
    Checking MUMmer programs found in path:
       NOT FOUND        nucmer
       NOT FOUND        show-coords
       NOT FOUND        show-snps
       NOT FOUND        delta-filter
    Cannot install because some programs from the MUMer package not found.
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-ha4k5x9b/pymummer
```

Is there a fix for this available?

**Comment by rc-reding** [comment]
I don't know if this has changed, but the programs are now named (as of mummer 4.0rc1) mummer-nucmer, mummer-show-coords, etc. So, in setup.py, you need you change 

`required_progs = ['nucmer', 'show-coords', 'show-snps', 'delta-filter']`

with this

`required_progs = ['mummer-nucmer', 'mummer-show-coords', 'mummer-show-snps', 'mummer-delta-filter']`

Now `python setup.py test` should say it did detect mummer, and can be installed.

**Comment by Adamtaranto** [comment]
mummer4 doesn't seem to have "mummer-" as a prefix on the old package names.

OP just needed to install mummer before installing pymummer.

This can be closed.
